name: Bug Report
description: Report a bug in TUI Commander
title: "[Bug] "
labels: ["type: bug", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of what the bug is.
      placeholder: What happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Open TUI Commander
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem.
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: dropdown
    id: build
    attributes:
      label: Build type
      description: How are you running TUI Commander?
      options:
        - Release build (compiled .app / .exe)
        - Dev mode (tauri dev)
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: TUI Commander version (check Settings or About)
      placeholder: "e.g. 0.3.0"
    validations:
      required: true
