name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["type: feature", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for TUICommander? We'd love to hear it!

  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this feature solve? What's your use case?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've considered?
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which part of TUICommander does this relate to?
      options:
        - Terminal / PTY
        - Sidebar / Repository management
        - Git / Worktrees
        - GitHub integration
        - Agent management
        - UI / Layout
        - MCP / Remote access
        - Other
    validations:
      required: true
