import { createTabManager, type BaseTab } from "./tabManager";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** File-based markdown tab (reads content from the filesystem via Tauri) */
export interface FileTab extends BaseTab {
  type: "file";
  repoPath: string;
  filePath: string;
  /** Display name (basename of filePath) */
  fileName: string;
}

/** Virtual markdown tab (content generated by a plugin via markdownProviderRegistry) */
export interface VirtualTab extends BaseTab {
  type: "virtual";
  title: string;
  /** URI routed through markdownProviderRegistry, e.g. "plan:file?path=/foo.md" */
  contentUri: string;
}

/** Discriminated union of all markdown tab types */
export type MdTabData = FileTab | VirtualTab;

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

function createMdTabsStore() {
  const base = createTabManager<MdTabData>();

  return {
    state: base.state,
    remove: base.remove,
    setActive: base.setActive,
    clearAll: base.clearAll,
    get: base.get,
    getIds: base.getIds,
    getActive: base.getActive,
    getCount: base.getCount,

    /** Add a file-based markdown tab (or return existing if same file already open) */
    add(repoPath: string, filePath: string): string {
      const existing = Object.values(base.state.tabs).find(
        (tab) => tab.type === "file" && tab.repoPath === repoPath && tab.filePath === filePath,
      ) as FileTab | undefined;
      if (existing) {
        base.setActive(existing.id);
        return existing.id;
      }

      const id = base._nextId("md");
      const fileName = filePath.split("/").pop() || filePath;
      return base._addTab({ type: "file", id, repoPath, filePath, fileName } as FileTab);
    },

    /** Add a virtual markdown tab (or return existing if same contentUri already open) */
    addVirtual(title: string, contentUri: string): string {
      const existing = Object.values(base.state.tabs).find(
        (tab) => tab.type === "virtual" && tab.contentUri === contentUri,
      ) as VirtualTab | undefined;
      if (existing) {
        base.setActive(existing.id);
        return existing.id;
      }

      const id = base._nextId("md");
      return base._addTab({ type: "virtual", id, title, contentUri } as VirtualTab);
    },

    /** Clear all file-based markdown tabs for a repository (virtual tabs are unaffected) */
    clearForRepo(repoPath: string): void {
      base._clearWhere((tab) => tab.type === "file" && (tab as FileTab).repoPath === repoPath);
    },

    /** Get file-based tabs for a specific repository */
    getForRepo(repoPath: string): FileTab[] {
      return Object.values(base.state.tabs).filter(
        (tab): tab is FileTab => tab.type === "file" && tab.repoPath === repoPath,
      );
    },
  };
}

export const mdTabsStore = createMdTabsStore();
