import { createStore, produce } from "solid-js/store";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** File-based markdown tab (reads content from the filesystem via Tauri) */
export interface FileTab {
  type: "file";
  id: string;
  repoPath: string;
  filePath: string;
  /** Display name (basename of filePath) */
  fileName: string;
}

/** Virtual markdown tab (content generated by a plugin via markdownProviderRegistry) */
export interface VirtualTab {
  type: "virtual";
  id: string;
  title: string;
  /** URI routed through markdownProviderRegistry, e.g. "plan:file?path=/foo.md" */
  contentUri: string;
}

/** Discriminated union of all markdown tab types */
export type MdTabData = FileTab | VirtualTab;

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

interface MdTabsStoreState {
  tabs: Record<string, MdTabData>;
  activeId: string | null;
  counter: number;
}

function createMdTabsStore() {
  const [state, setState] = createStore<MdTabsStoreState>({
    tabs: {},
    activeId: null,
    counter: 0,
  });

  const actions = {
    /** Add a file-based markdown tab (or return existing if same file already open) */
    add(repoPath: string, filePath: string): string {
      const existing = Object.values(state.tabs).find(
        (tab) => tab.type === "file" && tab.repoPath === repoPath && tab.filePath === filePath
      ) as FileTab | undefined;
      if (existing) {
        setState("activeId", existing.id);
        return existing.id;
      }

      const id = `md-${state.counter + 1}`;
      const fileName = filePath.split("/").pop() || filePath;
      setState("counter", (c) => c + 1);
      setState("tabs", id, { type: "file", id, repoPath, filePath, fileName } as FileTab);
      setState("activeId", id);
      return id;
    },

    /** Add a virtual markdown tab (or return existing if same contentUri already open) */
    addVirtual(title: string, contentUri: string): string {
      const existing = Object.values(state.tabs).find(
        (tab) => tab.type === "virtual" && tab.contentUri === contentUri
      ) as VirtualTab | undefined;
      if (existing) {
        setState("activeId", existing.id);
        return existing.id;
      }

      const id = `md-${state.counter + 1}`;
      setState("counter", (c) => c + 1);
      setState("tabs", id, { type: "virtual", id, title, contentUri } as VirtualTab);
      setState("activeId", id);
      return id;
    },

    /** Remove a markdown tab */
    remove(id: string): void {
      setState(
        produce((s) => {
          delete s.tabs[id];
          if (s.activeId === id) {
            const remaining = Object.keys(s.tabs);
            s.activeId = remaining.length > 0 ? remaining[remaining.length - 1] : null;
          }
        })
      );
    },

    /** Set the active markdown tab */
    setActive(id: string | null): void {
      setState("activeId", id);
    },

    /** Clear all file-based markdown tabs for a repository (virtual tabs are unaffected) */
    clearForRepo(repoPath: string): void {
      setState(
        produce((s) => {
          const idsToRemove = Object.values(s.tabs)
            .filter((tab) => tab.type === "file" && (tab as FileTab).repoPath === repoPath)
            .map((tab) => tab.id);

          for (const id of idsToRemove) {
            delete s.tabs[id];
          }

          if (s.activeId && idsToRemove.includes(s.activeId)) {
            s.activeId = null;
          }
        })
      );
    },

    /** Clear all markdown tabs (file and virtual) */
    clearAll(): void {
      setState({ tabs: {}, activeId: null, counter: state.counter });
    },

    /** Get a tab by ID */
    get(id: string): MdTabData | undefined {
      return state.tabs[id];
    },

    /** Get all tab IDs */
    getIds(): string[] {
      return Object.keys(state.tabs);
    },

    /** Get file-based tabs for a specific repository */
    getForRepo(repoPath: string): FileTab[] {
      return Object.values(state.tabs).filter(
        (tab): tab is FileTab => tab.type === "file" && tab.repoPath === repoPath
      );
    },

    /** Get active tab */
    getActive(): MdTabData | undefined {
      return state.activeId ? state.tabs[state.activeId] : undefined;
    },

    /** Get count of all tabs (file + virtual) */
    getCount(): number {
      return Object.keys(state.tabs).length;
    },
  };

  return { state, ...actions };
}

export const mdTabsStore = createMdTabsStore();
