//! Idempotent installer for native-agent settings-hooks (Claude, Gemini, Codex…).
//!
//! Writes the hook commands generated by [`crate::agent_hook`] into an agent's
//! JSON settings file and removes them again on demand. Ownership is decided
//! solely by the `# tuic-managed-hook` sentinel embedded in each command, so the
//! installer touches ONLY TUIC's entries — user and wiz hooks in the same file
//! are never read incorrectly, reordered, or destroyed.
//!
//! Invariants:
//! - **Single read-modify-write.** Load → prune our entries → append canonical
//!   groups → atomic write. The file is written exactly once, never on an error
//!   path, so a malformed settings file is reported (not corrupted).
//! - **Idempotent.** Installing twice equals installing once (prune-then-append).
//! - **Clean uninstall.** Pruning removes only sentineled commands and drops the
//!   groups/events that became empty as a result, leaving the file as if TUIC was
//!   never there.

use crate::agent_hook::{HookEntry, SENTINEL};
use serde_json::{Map, Value};
use std::path::Path;

/// Whether TUIC's hooks are present in a settings file, and current.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum InstallState {
    /// No TUIC-managed hooks present.
    NotInstalled,
    /// TUIC hooks present and byte-identical to the expected map.
    Installed,
    /// TUIC hooks present but differ from the expected map (older version).
    Outdated,
}

impl InstallState {
    /// Stable wire string for the frontend/HTTP (camelCase, matches the TS union).
    pub(crate) fn as_str(self) -> &'static str {
        match self {
            InstallState::NotInstalled => "notInstalled",
            InstallState::Installed => "installed",
            InstallState::Outdated => "outdated",
        }
    }
}

fn is_tuic_managed(cmd: &str) -> bool {
    cmd.contains(SENTINEL)
}

/// Load the settings file as a JSON object, or a fresh empty object if the file
/// is missing or blank. Errors (leaving the file untouched) if the root exists
/// but is not a JSON object.
fn load_root(path: &Path) -> Result<Map<String, Value>, String> {
    if !path.exists() {
        return Ok(Map::new());
    }
    let bytes = std::fs::read(path).map_err(|e| format!("read {}: {e}", path.display()))?;
    if bytes.iter().all(u8::is_ascii_whitespace) {
        return Ok(Map::new());
    }
    match serde_json::from_slice(&bytes).map_err(|e| format!("parse {}: {e}", path.display()))? {
        Value::Object(m) => Ok(m),
        _ => Err(format!("{} root is not a JSON object", path.display())),
    }
}

/// Serialize and write atomically (0600, temp+rename via `config::persist_atomic`).
fn write_root(path: &Path, root: &Map<String, Value>) -> Result<(), String> {
    let bytes = serde_json::to_vec_pretty(&Value::Object(root.clone()))
        .map_err(|e| format!("serialize settings: {e}"))?;
    crate::config::persist_atomic(path, &bytes)
}

/// Remove every TUIC-managed command from all event groups, then drop the groups
/// and events that this pruning left empty (so the file is restored exactly).
/// A user's group that merely contained a TUIC command keeps its other hooks; a
/// group/event that was entirely ours disappears.
fn prune_managed(hooks: &mut Map<String, Value>) {
    for groups in hooks.values_mut() {
        let Value::Array(arr) = groups else { continue };
        arr.retain_mut(|group| {
            let Some(inner) = group.get_mut("hooks").and_then(Value::as_array_mut) else {
                return true; // unrecognized shape — never touch it
            };
            let before = inner.len();
            inner.retain(|h| {
                h.get("command")
                    .and_then(Value::as_str)
                    .map(|c| !is_tuic_managed(c))
                    .unwrap_or(true)
            });
            // Drop the group only if WE emptied it (had hooks, now none).
            !(inner.is_empty() && before != inner.len())
        });
    }
    hooks.retain(|_event, groups| groups.as_array().map(|a| !a.is_empty()).unwrap_or(true));
}

/// Append `{matcher, hooks:[{type:command, command}]}` under `event`.
fn append_group(hooks: &mut Map<String, Value>, event: &str, matcher: &str, cmd: &str) {
    let entry = hooks
        .entry(event.to_string())
        .or_insert_with(|| Value::Array(Vec::new()));
    if let Some(arr) = entry.as_array_mut() {
        arr.push(serde_json::json!({
            "matcher": matcher,
            "hooks": [ { "type": "command", "command": cmd } ],
        }));
    }
}

/// Install the hook map into `settings`, preserving every non-TUIC entry.
pub(crate) fn install(settings: &Path, map: &[HookEntry]) -> Result<(), String> {
    let mut root = load_root(settings)?;
    {
        let hooks = match root
            .entry("hooks".to_string())
            .or_insert_with(|| Value::Object(Map::new()))
        {
            Value::Object(m) => m,
            _ => return Err(format!("{} `hooks` is not a JSON object", settings.display())),
        };
        prune_managed(hooks); // idempotency: drop any prior install first
        for (event, matcher, cmd) in map {
            append_group(hooks, event, matcher, cmd);
        }
    }
    write_root(settings, &root)
}

/// Remove every TUIC-managed hook from `settings`, leaving user hooks intact.
/// A missing file is a no-op.
pub(crate) fn uninstall(settings: &Path) -> Result<(), String> {
    if !settings.exists() {
        return Ok(());
    }
    let mut root = load_root(settings)?;
    match root.get_mut("hooks") {
        Some(Value::Object(hooks)) => prune_managed(hooks),
        Some(_) => return Err(format!("{} `hooks` is not a JSON object", settings.display())),
        None => return Ok(()),
    }
    // Drop an emptied `hooks` key so the file is left pristine.
    if root
        .get("hooks")
        .and_then(Value::as_object)
        .map(Map::is_empty)
        .unwrap_or(false)
    {
        root.remove("hooks");
    }
    write_root(settings, &root)
}

/// Report whether the file's TUIC hooks match `map`.
pub(crate) fn install_state(settings: &Path, map: &[HookEntry]) -> InstallState {
    let Ok(root) = load_root(settings) else {
        return InstallState::NotInstalled;
    };
    let Some(hooks) = root.get("hooks").and_then(Value::as_object) else {
        return InstallState::NotInstalled;
    };
    let mut present: Vec<String> = Vec::new();
    for groups in hooks.values() {
        let Some(arr) = groups.as_array() else { continue };
        for group in arr {
            let Some(inner) = group.get("hooks").and_then(Value::as_array) else {
                continue;
            };
            for h in inner {
                if let Some(c) = h.get("command").and_then(Value::as_str)
                    && is_tuic_managed(c)
                {
                    present.push(c.to_string());
                }
            }
        }
    }
    if present.is_empty() {
        return InstallState::NotInstalled;
    }
    let mut expected: Vec<String> = map.iter().map(|(_, _, c)| c.clone()).collect();
    present.sort();
    expected.sort();
    if present == expected {
        InstallState::Installed
    } else {
        InstallState::Outdated
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;
    use tempfile::TempDir;

    fn write(path: &Path, v: &Value) {
        std::fs::write(path, serde_json::to_vec_pretty(v).unwrap()).unwrap();
    }
    fn read(path: &Path) -> Value {
        serde_json::from_slice(&std::fs::read(path).unwrap()).unwrap()
    }
    /// A settings file with a pre-existing user hook + an unrelated top-level key.
    fn user_hook_file() -> Value {
        json!({
            "hooks": {
                "PreToolUse": [
                    { "matcher": "Bash", "hooks": [ { "type": "command", "command": "wiz-guard.sh" } ] }
                ]
            },
            "otherKey": 42
        })
    }
    fn count_tuic(v: &Value) -> usize {
        let mut n = 0;
        if let Some(h) = v.get("hooks").and_then(|h| h.as_object()) {
            for groups in h.values() {
                let Some(arr) = groups.as_array() else { continue };
                for g in arr {
                    let Some(inner) = g.get("hooks").and_then(|x| x.as_array()) else { continue };
                    for hk in inner {
                        if hk
                            .get("command")
                            .and_then(|c| c.as_str())
                            .map(is_tuic_managed)
                            .unwrap_or(false)
                        {
                            n += 1;
                        }
                    }
                }
            }
        }
        n
    }

    #[test]
    fn install_keeps_user_hook_and_adds_ours() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("settings.json");
        write(&path, &user_hook_file());
        let map = crate::agent_hook::claude_hook_map();
        install(&path, &map).unwrap();
        let v = read(&path);
        let pre = v["hooks"]["PreToolUse"].as_array().unwrap();
        assert!(
            pre.iter().any(|g| g["hooks"][0]["command"] == "wiz-guard.sh"),
            "user hook must survive install"
        );
        assert_eq!(v["otherKey"], 42, "unrelated keys preserved");
        assert_eq!(count_tuic(&v), map.len(), "all our hooks added");
    }

    #[test]
    fn install_twice_equals_once() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("settings.json");
        write(&path, &user_hook_file());
        let map = crate::agent_hook::claude_hook_map();
        install(&path, &map).unwrap();
        let once = read(&path);
        install(&path, &map).unwrap();
        let twice = read(&path);
        assert_eq!(once, twice, "install must be idempotent");
        assert_eq!(count_tuic(&twice), map.len(), "no duplicate tuic hooks");
    }

    #[test]
    fn uninstall_removes_only_ours_byte_for_byte() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("settings.json");
        let original = user_hook_file();
        write(&path, &original);
        let map = crate::agent_hook::claude_hook_map();
        install(&path, &map).unwrap();
        assert!(count_tuic(&read(&path)) > 0);
        uninstall(&path).unwrap();
        let after = read(&path);
        assert_eq!(count_tuic(&after), 0, "all tuic hooks removed");
        assert_eq!(after, original, "file restored as if TUIC was never there");
    }

    #[test]
    fn install_creates_missing_file() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("nested/settings.json");
        assert!(!path.exists());
        let map = crate::agent_hook::claude_hook_map();
        install(&path, &map).unwrap();
        assert!(path.exists(), "missing file must be created");
        assert_eq!(count_tuic(&read(&path)), map.len());
    }

    #[test]
    fn non_object_root_errs_and_leaves_file_untouched() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("settings.json");
        std::fs::write(&path, b"[1,2,3]").unwrap();
        let before = std::fs::read(&path).unwrap();
        let map = crate::agent_hook::claude_hook_map();
        assert!(install(&path, &map).is_err(), "non-object root must error");
        assert_eq!(
            std::fs::read(&path).unwrap(),
            before,
            "file must be untouched on error"
        );
    }

    #[test]
    fn non_object_hooks_errs_and_leaves_file_untouched() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("settings.json");
        std::fs::write(&path, br#"{"hooks": "nope"}"#).unwrap();
        let before = std::fs::read(&path).unwrap();
        let map = crate::agent_hook::claude_hook_map();
        assert!(install(&path, &map).is_err(), "non-object hooks must error");
        assert_eq!(std::fs::read(&path).unwrap(), before);
    }

    #[test]
    fn install_state_not_installed_then_installed_then_outdated() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("settings.json");
        write(&path, &user_hook_file());
        let map = crate::agent_hook::claude_hook_map();
        assert_eq!(install_state(&path, &map), InstallState::NotInstalled);
        install(&path, &map).unwrap();
        assert_eq!(install_state(&path, &map), InstallState::Installed);
        let newer: Vec<HookEntry> = vec![("Stop", "", format!("new-cmd {SENTINEL}"))];
        assert_eq!(install_state(&path, &newer), InstallState::Outdated);
    }
}
